---
- name: setup web server
  hosts: ec2-13-233-134-169.ap-south-1.compute.amazonaws.com
  become: yes
  tasks:
    - name: installing apache httpd service
      apt:
        name: httpd
        state: present
    - name: start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes
        update_cache: yes
