---
- name: setup web server
  hosts: 13.233.134.169
  become: yes
  tasks:
    - name: installing apache httpd service
      apt:
        name: httpd
        state: present
    - name: start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes
        update_cache: yes
